@startuml

left to right direction

actor "Funcionário/Administrador" as Admin
actor Espectador

rectangle "Sistema Cinema" {

  usecase "Cadastrar Cinema" as UC1
  usecase "Cadastrar Filme" as UC2
  usecase "Cadastrar Sessão" as UC3
  usecase "Registrar Público" as UC4
  usecase "Consultar Relatórios" as UC5

  usecase "Consultar Filmes em Cartaz" as UC6
  usecase "Consultar Sessões" as UC7
  usecase "Consultar Informações do Filme" as UC8
}

Admin --> UC1
Admin --> UC2
Admin --> UC3
Admin --> UC4
Admin --> UC5

Espectador --> UC6
Espectador --> UC7
Espectador --> UC8

@enduml
